### ISSUE TITLE
3.43.1 not in github

### ISSUE THREAD

**Issue by christophacham** [pulumi/homebrew-tap#11] opened 2022-10-15 16:54 UTC
### What happened?

➜  
```bash
~ brew install pulumi/tap/pulumi`
==> Downloading https://github.com/pulumi/pulumi/releases/download/v3.43.1/pulumi-v3.43.1-darwin-arm64.tar.gz
curl: (22) The requested URL returned error: 404                              

Error: pulumi: Failed to download resource "pulumi"
Download failed: https://github.com/pulumi/pulumi/releases/download/v3.43.1/pulumi-v3.43.1-darwin-arm64.tar.gz
```

---

when checking out the releases in GitHub the latest is v3.43.0: 
https://github.com/pulumi/pulumi/releases

![image](https://user-images.githubusercontent.com/32296133/195998540-5ed934f8-0469-44c4-bfbb-b1a33051c815.png)

### Steps to reproduce
```
brew install pulumi/tap/pulumi
```
### Expected Behavior

v3.43.1 is present in GitHub pulumi/pulumi and the download works.

### Actual Behavior

404 Not found the release is not found.

### Output of `pulumi about`

![image](https://user-images.githubusercontent.com/32296133/195998580-104dd360-4d8e-4523-81de-6303fd7a3986.png)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment] 2022-10-17 20:20
Hi @christophacham Thanks for opening this issue! GitHub let me know this is your first time opening an issue in Pulumi/Pulumi! Welcome! 👋🏻 😄 

I think this issue is a duplicate of https://github.com/pulumi/pulumi/issues/11041. If I'm correct, @AaronFriel fixed this issue over the weekend. I ran `brew install pulumi/tap/pulumi` and it worked for me, which leads me to believe the problem has been fixed.

Can you confirm the issue has been addressed for you?

**Closed** 2023-04-01 01:01 UTC
Labels: kind/bug, resolution/duplicate, impact/regression, awaiting-feedback
